### ISSUE TITLE
register.py: Don't reconfig if condor_master isn't running

### ISSUE THREAD

**Issue by jasoncpatton** [HTPhenotyping/registration#56]
For the Docker install method, HTCondor isn't running when `register.py` is invoked. Everything still works, so the warning about not contacting the master/not being able to reconfig is not needed.

**Comment by jasoncpatton** [comment]
More late-night fiddling as I'm approaching having a Windows batch script...

```Attempting to get token (attempt 1/10) ...
Token request is queued with ID 9605309.
Go to this URL in your web browser (copy and paste it into the address bar) and approve the request by clicking "Approve":
https://htpheno-cm.chtc.wisc.edu/token?code=9605309
Token request approved!
Traceback (most recent call last):
  File "/register.py", line 298, in <module>
    main()
  File "/register.py", line 103, in main
    reconfig()
  File "/register.py", line 236, in reconfig
    if not condor_master_is_alive():
  File "/register.py", line 276, in condor_master_is_alive
    return who_ad["MASTER"] == "Alive"
KeyError: 'MASTER'
Error: Encountered unhandled error: 'MASTER'
Consider re-running with --verbose to see debugging information.```

**Comment by JoshKarpel** [comment]
Yuck... I figured that if it parsed the ad must have all the data in it. I'll put some better error handling on it tomorrow.
